# Generated by Django 5.0.2 on 2024-02-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=20, verbose_name='Логин')),
                ('Status', models.CharField(max_length=100, verbose_name='Статус')),
                ('About', models.TextField(verbose_name='О себе')),
                ('Date', models.DateTimeField(verbose_name='Дата регистрации')),
            ],
        ),
    ]
